### ISSUE TITLE
Any new code releases?

### ISSUE THREAD

**Issue by Ravenwater** [You1991/MICSVM#1]
We are working on custom hardware-based SVM for embedded intelligence applications and we would like to compare our solution to Xeon, Phi, and GPU. The paper is published, so is there a new release of the code that the community can bootstrap from?

**Comment by fastalgo** [comment]
Please check the new code at https://github.com/fastalgo/casvm

**Comment by Ravenwater** [comment]
Thank you. communication avoidance, love it.
